### ISSUE TITLE
Better ergonomics for implementing Koto functions / types in Rust

### ISSUE THREAD

**Issue by jasal82** [koto-lang/koto#259]
Please add some macros for adding new functions to KMaps and for defining and registering custom types. IMHO the interface is too complicated and verbose at the moment.

**Comment by irh** [comment]
Hey @jasal82, I'd like to make it as simple as possible to define custom types, and it would be very helpful to hear from you what you've found complicated / too verbose. I assume you've found `ObjectEntryBuilder`?

**Comment by jasal82** [comment]
It would also be very convenient if Koto could unpack the arguments automatically and convert them to the expected function argument types. I've switched between different embedded languages in my project in the past few months and the required changes to the module implementations were always manageable. For the transition to Koto, however, I had to basically rewrite the modules from scratch.

**Comment by irh** [comment]
I see, thanks for the pointer. I hadn't seen Rune's approach but I do like the idea of macros that take care of matching types for the straightforward cases. If you've tried other languages with nice APIs then please point me their way too =) 

I consider making the API as ergonomic as possible a mid-term goal, but secondary to language ergonomics and performance, so I've been waiting on making the language as stable as possible, and I'm hesitant to dive into hiding the underlying machinery via macros while things are in flux. If it's any consolation you should have seen what things were like before I added the entry builder 😆

**Comment by jasal82** [comment]
Hehe I better not browse the history then... I'm perfectly fine with your approach. Thankfully Copilot is here to assist me with the boring API migration.

**Comment by irh** [comment]
I've made a PR that introduces macros that make it easier to implement custom object types, see #269.

I haven't gone as far as detecting argument types, but this is a step in the right direction, and can be extended later on with more ergonomic tweaks if needed. 

I'll close this issue and then new issues can be opened for specific improvements.
