### ISSUE TITLE
Mapping unclonable Rust types to Koto

### ISSUE THREAD

**Issue by jasal82** [koto-lang/koto#262]
What is the recommended way of mapping unclonable types to Koto? Ideally I would like to map them to an unclonable type in Koto as well, but I'm not sure if this is possible because

- I have to implement `copy()` in the `impl KotoObject`
- Some methods need to move out of the instance, but the current API doesn't allow that

For example I need this type in the Koto API so that I can interact with a HTTP response:

```
struct Response(ureq::Response);
```

**Comment by irh** [comment]
Oh by the way, I've been thinking about how to add async tasks to Koto which might be interesting to you if you're working with web requests, I'll write it up once I get a moment.

**Comment by irh** [comment]
Yeah it's worth reading up on the different wrapper types and how they attach behaviour to your type. In your case I think I would try something like a `Rc<RefCell<Option<Response>>>` (or `koto_memory::PtrMut<Option<Response>>`)..

- `Rc` -> cloneable
- `RefCell` -> runtime-checked mutability
- `Option` -> allows the inner value to be moved away, leaving `None` in its place
