### ISSUE TITLE
[request] Add raw strings

### ISSUE THREAD

**Issue by jasal82** [koto-lang/koto#263]
This could be helpful for embedding multiline text or for writing regex patterns. Something like the Rust raw string syntax or Python triple quotes would be fine I guess.

**Comment by jasal82** [comment]
Didn't know that multiline strings are already supported, thanks for the info. Btw, I created a regex module. If you're interested I can open a PR to contribute to the core lib.

**Comment by irh** [comment]
Great! I think regex would be a good fit for the extra modules in `/libs/`, a PR would be welcome 👍
