### ISSUE TITLE
[bug] Project doesn't build on Windows

### ISSUE THREAD

**Issue by jasal82** [koto-lang/koto#264]
I get multiple errors like the following:

```
error: couldn't read C:\Projects\git\koto\core\cli/docs/core_lib/range.md
```

There is a `docs` file in the `core/cli` folder with content `../../docs` so I think this is supposed to be a symlink which doesn't work as intended on Windows.

**Comment by jasal82** [comment]
```
  --> core\cli\src\help.rs:23:17
   |
23 |                 include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/", $doc))
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
57 |             include_doc!("core_lib/range.md"),
   |             --------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `include_str` which comes from the expansion of the macro `include_doc` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by alisomay** [comment]
From the first look it looks like a forward and backslash mixture issue probably could be resolved with an approach of some sort:

```rust
        #[cfg(not(target_os = "windows"))]
        macro_rules! include_doc {
            ($doc:expr) => {
                // Including via a symlink to the top-level docs folder to ensure cargo-package
                // can find it during packaging.
                include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/docs/", $doc))
            };
        }
        
        #[cfg(target_os = "windows")]
        macro_rules! include_doc {
            ($doc:expr) => {
                include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "\\docs\\", $doc.replace("/", "\\")))
            };
        }
```

**Comment by irh** [comment]
@jasal82 Building with Windows on CI is [working correctly](https://github.com/koto-lang/koto/actions/runs/7192956454/job/19590437799). Do you have git symlinks enabled? `git config --get core.symlinks`?

@alisomay Thanks, although forward slashes in `include_str` should work correctly with Windows too.

**Comment by irh** [comment]
FWIW the symlink is being used to allow the CLI to [bundle the docs in a way that cargo-package can understand](https://github.com/koto-lang/koto/blob/main/core/cli/src/help.rs#L21-L23). There might be a less brittle approach but I didn't investigate further, certainly it would be nice to avoid the symlink if possible.

**Comment by jasal82** [comment]
@irh AFAIK the `core.symlinks` settings requires either developer mode or a specific policy setting to be enabled on Windows. I cannot do that on my company laptop.

**Comment by irh** [comment]
I see, well that's a problem! I'll look into another approach as soon as I have a moment. As a temporary workaround if you like you can simply replace the symlink with a copy of the `docs` folder.
