### ISSUE TITLE
[request] Add list/tuple slicing

### ISSUE THREAD

**Issue by jasal82** [koto-lang/koto#267]
As far as I can see there is no way of slicing lists or tuples. I think this is essential for a broad range of algorithms and should be supported. This could for example be implemented on top of the index operator like in Python:

```
mylist = [1,2,3]
slice1 = mylist[1:] # == [2,3]
slice2 = mylist[:-1] # == [1,2]
```

A separate slicing function would also be ok I guess.

**Comment by jasal82** [comment]
It could also be possible to build this on top of the range types to make it more similar to Rust. But then we'd have open ranges like `1..` which are no longer iterable as required by the current design.

**Comment by irh** [comment]
This is actually supported (except for negative indices) for Lists, Tuples, and Strings. I must have forgotten to add it to the guide.

```
x = (0..5).to_list()
print x[3..] 
#  [3, 4]
print x[..2]
# [0, 1]
print 'hello'[1..=3]
# ell
```

When used with Tuples and Strings, the slices reuse the original data. Slicing with a List creates a new list.

I'll leave the issue open as a reminder to add documentation.

**Comment by jasal82** [comment]
Just out of curiosity, is `3..` also a valid value for a range?

**Comment by irh** [comment]
Yes, that's also info that's missing from the guide. 

https://koto.dev/play/?gist=ae829c42f2436b476729446fa08d3ca6

```ruby
range_info = |r|
  print '${r}\tstart: ${r.start()}, end: ${r.end()}, inclusive: ${r.is_inclusive()}'

range_info 10..
range_info ..99
range_info ..=10
range_info ..

# 10..	start: 10, end: null, inclusive: false
# ..99	start: null, end: 99, inclusive: false
# ..=10	start: null, end: 10, inclusive: true
# ..	start: null, end: null, inclusive: false
```

In Rust code you can check [KRange::is_bounded](https://docs.rs/koto_runtime/latest/koto_runtime/struct.KRange.html#method.is_bounded) to see if the range coming from Koto has a defined start and end.
