### ISSUE TITLE
Any plans for safe embedding?

### ISSUE THREAD

**Issue by stephanemagnenat** [koto-lang/koto#288]
Hello, this is a nice project!

I have a question regarding the plans for safe embedding. For example, at the moment the following code crashes the Playground:
```
a = 0
while 0 == 0
```

So is there plans for things like:
- limit in number of "iterations" in one VM run (e.g., number of AST node visit)
- limit in memory (stack, heap, etc.)
- limits in parsing (i.e., making sure that the parsing either terminates or fails within a certain amount of time and memory)

These would be important for using Koto to run un-trusted user code in an application.

**Comment by irh** [comment]
Hi @stephanemagnenat 👋

I can see the need for being able to place limits on all of the above for untrusted code, although I don't have any plans at the moment. 

Some thoughts:

> limit in number of "iterations" in one VM run (e.g., number of AST node visit)

I guess this would be easy enough to implement via a counter check in `Vm::execute_instructions`. 

> limits in parsing (i.e., making sure that the parsing either terminates or fails within a certain amount of time and memory)

Similarly, a counter in `Parser::push_node_with_span` could be checked, bailing out if a node limit is reached.

> limit in memory (stack, heap, etc.)

This is the hardest to get right I think. Koto allocates freely using the global allocator. A VM stack size limit could be introduced, although I'm not sure how useful it would be? Limits on the core container sizes could also be introduced.

Thanks for the nudge to think more deeply about this, I've been thinking more about trusted-code use cases, although as you point out it's easy to get the playground into a bad state, and I'd certainly like to improve that as a starting point.

**Comment by irh** [comment]
@stephanemagnenat I went ahead in #289 and added a timeout feature to the VM which allows you to define a maximum execution duration for a VM run.

I'm inclined to close this issue now, and then I'll be open to addressing other safety concerns in issues based on specific scenarios.
