### ISSUE TITLE
`koto_tests::strings` fails when escaping a newline

### ISSUE THREAD

**Issue by Rafferty97** [koto-lang/koto#315]
I have just cloned the repository and run `cargo test --test koto_tests`. I am on Windows.

The failing test case is as follows:
```
  @test escape: ||
    x = "
"
    if os.name() == "windows"
      assert_eq x.escape(), r"\r\n"
    else
      assert_eq x.escape(), r"\n"

    assert_eq "👋".escape(), r"\u{1f44b}"
```

The error is:
```
thread 'koto_tests::strings' panicked at crates\koto\tests\koto_tests.rs:44:17:
Error while running test 'escape': Assertion failed, '\n' is not equal to '\r\n'
--- \\?\C:\Users\alexa\dev\koto\koto\tests\strings.koto - 68:7
    |
 68 |       assert_eq x.escape(), r"\r\n"
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I believe the problem is that although I'm on Windows, my IDE is preserving the unix-like line endings in the file "strings.koto", and so when the string containing just a newline is escaped, it is escaped to "\n" only.

I think perhaps the test should simply be changed to expect "\n" in all cases, or alternatively, either "\n" or "\r\n" regardless of OS.

**Comment by irh** [comment]
Oh I see, yes we can't guarantee `\r\n` line endings in files on Windows, I'll update the test. Thanks for the report!
