### ISSUE TITLE
Mapping Rust code that implements the builder pattern

### ISSUE THREAD

**Issue by jasal82** [koto-lang/koto#344]
I have a lot of code that I want to make available as Koto functions/objects which uses the builder pattern in some way. Usually this means that there are methods which take ownership of `self`. However, in Koto this is not allowed. I can only make the method context borrow or mutably borrow `self`, which makes it necessary to construct ugly workarounds like this
```
use colored::{Color, ColoredString, Colorize};
use std::cell::RefCell;
use std::mem;

struct S {
    text: RefCell<ColoredString>,
}

impl S {
    fn blue(&self) -> &Self {
        let text = mem::take(&mut *self.text.borrow_mut());
        self.text.replace(text.color(Color::Blue));
        self
    }
}
```
to make it work with `koto_impl`/`koto_method` and avoid unnecessary cloning. Is there an easier solution for these cases or do you see a way to make this less cumbersome?

**Comment by irh** [comment]
I'm not sure if this will work for your exact situation, but I've been implementing a builder-like pattern with `MethodContext::instance_result`. 

See [this Koto code in bevy_koto](https://github.com/koto-lang/bevy_koto/blob/main/assets/scrolling_squares.koto#L51), which is implemented on the Rust side [like this](https://github.com/koto-lang/bevy_koto/blob/main/src/shape.rs#L197). There's also examples of how to use it in [the Color object](https://github.com/koto-lang/koto/blob/51c8589b59a8707921e99710c3909fa06c6473fc/libs/color/src/color.rs#L167) and in [Rect.set_center](https://github.com/koto-lang/koto/blob/51c8589b59a8707921e99710c3909fa06c6473fc/libs/geometry/src/rect.rs#L90).

The general idea is that the method context holds on to the outer Koto-friendly `KObject`, and then provides access to the inner data via the `instance`/`instance_mut` functions, and if you want the result of the function to be the object itself, then return `instance_result()`.

**Comment by jasal82** [comment]
Yep that's what I'm doing, but I still need a workaround for the non-copy types. Ideally I'd like to have something like
```
#[koto_method]
pub fn black(ctx: MethodContext<Self>) -> Result<KValue> {
  ctx.instance_move(|instance| instance.text.color(Color::Black))
}
```
but that doesn't exist (and I'm not 100% sure it would even be possible with Rust) so I need this:
```
#[koto_method]
pub fn black(ctx: MethodContext<Self>) -> Result<KValue> {
    let text = mem::take(&mut *ctx.instance_mut()?.text.borrow_mut());
    ctx.instance_mut()?.text.replace(text.color(Color::Black));
    ctx.instance_result()
}
```

**Comment by irh** [comment]
I'm not sure I've got the full picture here, but maybe having your `text` field be an `Option<ColoredString>` rather than a RefCell might be a better fit? You could use `Option::take` to move your field out (leaving `None` in the `Option`), and then put it back into the `Option` after processing?

**Comment by jasal82** [comment]
You're right, how could I miss the simple solution... This works just as well:
```
#[koto_method]
pub fn black(ctx: MethodContext<Self>) -> Result<KValue> {
    ctx.instance_mut()?.text = ctx.instance_mut()?.text.take().and_then(|t| Some(t.black()));
    ctx.instance_result()
}
```

**Comment by jasal82** [comment]
It would still be cool if the amount of work needed to expose existing code to Koto could be minimized. In Rune for example the macro attributes also support methods with `self` and `mut self` arguments. I don't really care about parameter type conversion magic to keep original signatures, but having all options in terms of `self` access semantics could be a great convenience boost.

**Comment by irh** [comment]
That's interesting, `self` or `mut self` would imply that you're dealing with the only instance of the data, which can't happen without something like a hidden call to `unwrap_or_clone`, and I'm not sure I'd want to hide work that's potentially very expensive (each step in a build chain would require a newly allocated clone of the data).
