### ISSUE TITLE
Strict spacing for maps?

### ISSUE THREAD

**Issue by unlessgames** [koto-lang/koto#368]
Hey, I really like what you are cooking here! Currently looking into koto to use as a live-coding language for a new framework.

Any particular reason the syntax is so strict about no-space before colons in maps, like error on `{a : 10}` in favor of `{a: 10}`? I feel like this is not aligned well with the otherwise forgiving and simple nature of the syntax.

**Comment by irh** [comment]
Hey @unlessgames 👋 Glad you like the look of it! Live-coding is one of the main reasons I made Koto, please let me know how you get on.

I think there isn't really a good reason for the syntax to be strict here, especially with inline maps where parsing is generally flexible.

It should be a relatively simple change. `peek_token` / `consume_token` can become `peek_next_token_on_same_line` / `consume_next_token_on_same_line` in [`parser.rs`](https://github.com/koto-lang/koto/blob/main/crates/parser/src/parser.rs#L1937-L1938)), go ahead and make a PR if you like, or I can get to it later on.

**Comment by unlessgames** [comment]
Neat, thanks! I submitted the PR.

**Comment by irh** [comment]
Thanks!
