### ISSUE TITLE
Is it possible to extend a primitive?

### ISSUE THREAD

**Issue by ales-tsurko** [koto-lang/koto#38]
On the language level. Say, adding a method to number or string?

**Comment by irh** [comment]
Yes, it's possible. 

The primitive methods are in modules (which are simply Maps) with corresponding names, and there's nothing stopping you from adding functions to them. 

e.g.

```coffee
import number, test.assert_eq

number.times_ten = |n| n * 10
assert_eq 10.times_ten(), 100
```

There's an [example of this in practice in the iterator tests](https://github.com/koto-lang/koto/blob/bef5ed224fa12975f9671db924fbe20cecbc18b3/koto/tests/iterators.koto#L160
), where a custom iterator adapter is created by inserting it into the `iterator` map.

If you want to add Rust functions to these modules they're stored in the 'prelude' map, which is exposed in the top-level `Koto::prelude()` getter. So, you can get the corresponding map by name from the prelude, and then add your own function in the same way as in the core library, e.g. see the implementation of [number.is_nan()](https://github.com/koto-lang/koto/blob/bef5ed224fa12975f9671db924fbe20cecbc18b3/src/runtime/src/core/number.rs#L65).

**Comment by ales-tsurko** [comment]
Cool! Thanks!
